//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_QuanLyBanGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int MaDG { get; set; }
        public string TenSP { get; set; }
        public int MaKhach { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
        public Nullable<int> DanhGiaStar { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
